#!/usr/bin/env bash
# PreToolUse(Edit|Write) hook: blocks manual edits to generated or tool-owned files.
# Exit 0 = allow, Exit 2 = block with message.
set -euo pipefail

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')
[ -z "$FILE_PATH" ] && exit 0

ROOT="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
REL="${FILE_PATH#"$ROOT"/}"

case "$REL" in
  public/sitemap.xml|public/sitemap-*.xml|public/robots.txt)
    echo "BLOCKED: $REL is generated by next-sitemap on 'yarn build' (postbuild). Edit next-sitemap.config.js instead." >&2
    exit 2 ;;
  next-env.d.ts)
    echo "BLOCKED: next-env.d.ts is regenerated by Next.js. Do not edit it." >&2
    exit 2 ;;
  .next/*|tsconfig.tsbuildinfo)
    echo "BLOCKED: $REL is build output. Do not edit it." >&2
    exit 2 ;;
  yarn.lock)
    echo "BLOCKED: yarn.lock is managed by Yarn. Run 'yarn add' / 'yarn install' instead." >&2
    exit 2 ;;
esac

exit 0
